class ImageConstants {
  static const String hotstarLogoPng =
      "assets/images/india_tab_images/disney_plus_hotstar_logo_1583901149861_1__1_-removebg-preview.png";
  static const String loginScreenPng = "assets/images/Login page hotstar.png";

  static const List indiaImagesList = [
    "assets/images/india_tab_images/BigBoss.jpeg",
    "assets/images/india_tab_images/mounaragam image.jpeg",
    "assets/images/india_tab_images/oscars.jpeg",
    "assets/images/india_tab_images/chembaneerpoovu image.jpeg",
    "assets/images/india_tab_images/geetha govindam image.jpeg",
    "assets/images/india_tab_images/kadothu kathoram image.jpeg",
    "assets/images/india_tab_images/etho janmakalpanayil image.jpeg",
    "assets/images/india_tab_images/Bheeshma parvam.jpeg",
    "assets/images/india_tab_images/chandrakantham image.jpeg",
    "assets/images/india_tab_images/gourishankar image.jpeg",
    "assets/images/india_tab_images/patharamattu image.jpeg",
    "assets/images/india_tab_images/Bahubali 2.jpeg",
    "assets/images/india_tab_images/kudumbavilakku image.jpeg",
    "assets/images/india_tab_images/Star singer s9.jpeg",
  ];
  static const List actionImagesList = [
    "assets/images/action_tab_images/Bheeshma parvam.jpeg",
    "assets/images/action_tab_images/Bahubali 2.jpeg",
    "assets/images/action_tab_images/rangasthalam.jpeg",
    "assets/images/action_tab_images/action hero biju.jpeg",
    "assets/images/action_tab_images/mersal.jpeg",
    "assets/images/action_tab_images/janatha garage.jpeg",
    "assets/images/action_tab_images/kammattipadam.jpeg",
    "assets/images/action_tab_images/pulimurugan.jpeg",
    "assets/images/action_tab_images/dead man's chest.jpeg",
    "assets/images/action_tab_images/king of kotha.jpeg",
    "assets/images/action_tab_images/national treasure 2.jpeg",
    "assets/images/action_tab_images/vaaliban.jpeg",
    "assets/images/action_tab_images/stranger tides.jpeg",
    "assets/images/action_tab_images/the curse of the pearl.jpeg",
  ];
  static const List comedyImagesList = [
    "assets/images/comedy_tab_images/abcd.jpeg",
    "assets/images/comedy_tab_images/adi kapyare kootamani.jpeg",
    "assets/images/comedy_tab_images/beware of dogs.jpeg",
    "assets/images/comedy_tab_images/big father.jpeg",
    "assets/images/comedy_tab_images/chunks.jpeg",
    "assets/images/comedy_tab_images/elemental.jpeg",
    "assets/images/comedy_tab_images/honey bee.jpeg",
    "assets/images/comedy_tab_images/kunjiramayanam.jpeg",
    "assets/images/comedy_tab_images/modern family.jpeg",
    "assets/images/comedy_tab_images/my boss.jpeg",
    "assets/images/comedy_tab_images/ringmaster.jpeg",
    "assets/images/comedy_tab_images/two countries.jpeg",
    "assets/images/comedy_tab_images/ustad hotel.jpeg",
    "assets/images/comedy_tab_images/vellimoonga.jpeg",
  ];
  static const List crimeImagesList = [
    "assets/images/crime_tab_images/ranam.jpeg",
    "assets/images/crime_tab_images/indian police.jpeg",
    "assets/images/crime_tab_images/kannur squad.jpeg",
    "assets/images/crime_tab_images/kerala crime files.jpeg",
    "assets/images/crime_tab_images/lsd.jpeg",
    "assets/images/crime_tab_images/mukundan unni associates.jpeg",
    "assets/images/crime_tab_images/bones the final chapter.jpeg",
    "assets/images/crime_tab_images/cruella.jpeg",
    "assets/images/crime_tab_images/d16.jpeg",
    "assets/images/crime_tab_images/death on the nile.jpeg",
    "assets/images/crime_tab_images/raid.jpeg",
    "assets/images/crime_tab_images/s india.jpeg",
    "assets/images/crime_tab_images/the big bull.jpeg",
    "assets/images/crime_tab_images/white collar.jpeg",
  ];
  static const List dramaImagesList = [
    "assets/images/drama_tab_images/amma manasu.jpeg",
    "assets/images/drama_tab_images/anuraga karikkin vellam.jpeg",
    "assets/images/drama_tab_images/aravindante athidhikal.jpeg",
    "assets/images/drama_tab_images/chandrakantham image.jpeg",
    "assets/images/drama_tab_images/etho janmakalpanayil image.jpeg",
    "assets/images/drama_tab_images/geetha govindam image.jpeg",
    "assets/images/drama_tab_images/kadothu kathoram image.jpeg",
    "assets/images/drama_tab_images/koodevide.jpeg",
    "assets/images/drama_tab_images/lollipop.jpeg",
    "assets/images/drama_tab_images/malikkappuram.jpeg",
    "assets/images/drama_tab_images/naga panchami.jpeg",
    "assets/images/drama_tab_images/njandukalude nattil oridavela.jpeg",
    "assets/images/drama_tab_images/parava.jpeg",
    "assets/images/drama_tab_images/patharamattu image.jpeg",
  ];
  static const List romanceImagesList = [
    "assets/images/romance_tab_images/bangalore days.jpeg",
    "assets/images/romance_tab_images/annayum rasoolum.jpeg",
    "assets/images/romance_tab_images/hridayathil sookshikkan.jpeg",
    "assets/images/romance_tab_images/dr love.jpeg",
    "assets/images/romance_tab_images/hridayam.jpeg",
    "assets/images/romance_tab_images/lovesongs.jpeg",
    "assets/images/romance_tab_images/mohabbath.jpeg",
    "assets/images/romance_tab_images/mounam sammatham.jpeg",
    "assets/images/romance_tab_images/mounam sammatham 3.jpeg",
    "assets/images/romance_tab_images/om shanthi oshana.jpeg",
    "assets/images/romance_tab_images/the story of us.jpeg",
    "assets/images/romance_tab_images/oru indian pranayakadha.jpeg",
    "assets/images/romance_tab_images/Premam.jpeg",
    "assets/images/romance_tab_images/the little mermaid.jpeg",
  ];
  static const List thrillerImagesList = [
    "assets/images/thriller_tab_images/kali.jpeg",
    "assets/images/thriller_tab_images/athiran.jpeg",
    "assets/images/thriller_tab_images/9.jpeg",
    "assets/images/thriller_tab_images/7th day.jpeg",
    "assets/images/thriller_tab_images/bhramaram.jpeg",
    "assets/images/thriller_tab_images/drishyam.jpeg",
    "assets/images/thriller_tab_images/iyobinte pusthakam.jpeg",
    "assets/images/thriller_tab_images/manichitrathazhu.jpeg",
    "assets/images/thriller_tab_images/memories.jpeg",
    "assets/images/thriller_tab_images/mumbai police.jpeg",
    "assets/images/thriller_tab_images/oru marubhoomi kadha.jpeg",
    "assets/images/thriller_tab_images/rakshasan.jpeg",
    "assets/images/thriller_tab_images/take off.jpeg",
    "assets/images/thriller_tab_images/varathan.jpeg",
  ];
  static const List horrorImagesList = [
    "assets/images/horror_tab_images/in ghost house inn.jpeg",
    "assets/images/horror_tab_images/7 rathrikal.jpeg",
    "assets/images/horror_tab_images/no one will save you.jpeg",
    "assets/images/horror_tab_images/ahs.jpeg",
    "assets/images/horror_tab_images/antlers.jpeg",
    "assets/images/horror_tab_images/goosebumps.jpeg",
    "assets/images/horror_tab_images/haunted mansion.jpeg",
    "assets/images/horror_tab_images/laxmi.jpeg",
    "assets/images/horror_tab_images/nighthouse.jpeg",
    "assets/images/horror_tab_images/the boogeyman.jpeg",
    "assets/images/horror_tab_images/the empty man.jpeg",
    "assets/images/horror_tab_images/the past.jpeg",
    "assets/images/horror_tab_images/the menu.jpeg",
    "assets/images/horror_tab_images/the hills have eyes 2.jpeg",
  ];
  static const List mySpaceProImagesList = [
    "assets/images/my_space_images/iron man logo.png",
    "assets/images/my_space_images/kids logo.png",
  ];
  static const List watchImagesList = [
    "assets/images/my_space_images/big boss.webp",
    "assets/images/my_space_images/avatar 2.webp",
    "assets/images/my_space_images/12 th fail.webp",
    "assets/images/my_space_images/the falcon and the winter soldier.webp",
    "assets/images/my_space_images/ppl.webp",
    "assets/images/my_space_images/antman 3.webp",
  ];
  static const List kidsImagesList = [
    "assets/images/kids_images/hindi 2.webp",
    "assets/images/kids_images/english.webp",
    "assets/images/kids_images/tamil 2.webp",
    "assets/images/kids_images/telugu.webp",
    "assets/images/kids_images/malayalam.webp",
    "assets/images/kids_images/bengali 2.webp",
    "assets/images/kids_images/marathi.webp",
    "assets/images/kids_images/kannada.webp",
  ];
  static const List languageLogoList = [
    "assets/images/kids_images/hindi.webp",
    "assets/images/kids_images/English logo.webp",
    "assets/images/kids_images/tamil.webp",
    "assets/images/kids_images/telugu 2.webp",
    "assets/images/kids_images/malayalam 2.webp",
    "assets/images/kids_images/bengali.webp",
    "assets/images/kids_images/marathi 2.webp",
    "assets/images/kids_images/kannada 2.webp",
  ];
  static const List homeImagesList = [
    "assets/images/home_screen_images/sliding_images/big boss.webp",
    "assets/images/home_screen_images/sliding_images/ng.webp",
    "assets/images/home_screen_images/sliding_images/neymar.webp",
    "assets/images/home_screen_images/sliding_images/mukundan unni.webp",
    "assets/images/home_screen_images/sliding_images/sulaikha mansil.webp",
    "assets/images/home_screen_images/sliding_images/palthu janwar.webp",
    "assets/images/home_screen_images/sliding_images/mrs perfect.webp",
  ];
  static const List floatImagesList = [
    "assets/images/home_screen_images/sliding_images/bigg boss logo.webp",
    "assets/images/home_screen_images/sliding_images/ng logo.webp",
    "assets/images/home_screen_images/sliding_images/neymar logo.webp",
    "assets/images/home_screen_images/sliding_images/mukundan unni logo.webp",
    "assets/images/home_screen_images/sliding_images/sulaikha mansil logo.webp",
    "assets/images/home_screen_images/sliding_images/palthu janwar logo.webp",
    "assets/images/home_screen_images/sliding_images/mrs perfect logo.webp",
  ];
}
